- name: Instalando...
  apt:
    name: ['apache2', 'libapache2-mod-php']
    state: present
    update_cache: yes

- name: Inicializando...
  service:
    name: apache2
    state: restarted
    enabled: yes
